homework:
    image: jiegec/router-lab-x86_64
    script:
        - mkdir logs
        - make -C Homework/checksum
        - (cd Homework/checksum && python3 grade.py | tee ../../logs/checksum.log)
        - make -C Homework/forwarding
        - (cd Homework/forwarding && python3 grade.py | tee ../../logs/forwarding.log)
        - make -C Homework/lookup
        - (cd Homework/lookup && python3 grade.py | tee ../../logs/lookup.log)
        - make -C Homework/protocol
        - (cd Homework/protocol && python3 grade.py | tee ../../logs/protocol.log)
    artifacts:
        paths:
            - logs
        when: always
        expire_in: 1 year

router:
    image: jiegec/router-lab-aarch64
    tags:
        - arm64
    script:
        - make -C Homework/router/r1
        - make -C Homework/router/r2
        - make -C Homework/router/r3
    artifacts:
        paths:
            - Homework/router/r1/router
            - Homework/router/r2/router
            - Homework/router/r3/router
        when: always
        expire_in: 1 year
